15web/symfony-starter-kit

- backend/migrations/Version20220603114543.php
- docker/mysql/mysql.cnf
> feat(docker): Исправил конфигурацию часового пояса в mysql.cnf

- .github/workflows/check-code-quality.yml
- docker/manage.bash
> feat(ci): Исправил сборку для ф. тестов

- docker/backend/Dockerfile
> feat(ci): Добавил git в образ backend

- backend/composer.lock
> feat(composer): Обновил пакеты

- backend/openapi.yaml
- backend/src/Infrastructure/ApiException/CreateExceptionJsonResponse.php
- backend/src/Infrastructure/ApiException/ExceptionEventSubscriber.php
- backend/src/Infrastructure/ApiException/di.php
- backend/src/User/Http/ApiTokenAuthenticator.php
- backend/src/User/Http/AuthenticationEntryPoint.php
- backend/src/User/Http/JsonLoginAuthenticator.php
- backend/src/User/Http/SignInAction.php
- backend/src/User/config.php
- backend/src/User/di.php
- backend/tests/Functional/User/SignInTest.php
> feat(user): Подключил кастомное исключение при ошибках аутентификации

- backend/tests/Functional/Task/TaskInfoTest.php
- backend/tests/Functional/Task/TaskListTest.php
> feat(task): Добавил тест по проверке доступа к чужим задачам

- backend/composer.json
- backend/composer.lock
- backend/config/packages/doctrine.yaml
- backend/phpunit.xml
- backend/tests/Command/SendUncompletedTaskCommandTest.php
- backend/tests/Functional/User/SignUpTest.php
- docker/manage.bash
> feat(paratest): Настройка параллельного запуска тестов

- backend/.env.test
- backend/bin/console
- backend/deptrac.yaml
- backend/phpcs.xml
- backend/phpcs/ruleset.xml
- backend/phpstan/object-manager.php
- backend/public/index.php
- backend/src/Infrastructure/Kernel.php
- backend/src/Infrastructure/di.php
> feat(kernel): WIP: Kernel // Перенес в Infrastructure

- README.md
> feat(clearProject): Добавил инструкцию по очистке, для старта проектов

- backend/composer.lock
- backend/src/Infrastructure/ApiRequestResolver/ApiRequestArgumentValueResolver.php
- backend/src/Infrastructure/OpenApiValidateSubscriber.php
- backend/symfony.lock
> feat(composerUpdate): Обновил симфони и все остальные пакеты

- backend/src/Infrastructure/OpenApiValidateSubscriber.php
> refactor(openApiValidate): Отрефакторил OpenApiValidateSubscriber, вынес дублирование в методы

- backend/php-cs-fixer-config.php
- backend/tests/Command/SendUncompletedTaskCommandTest.php
- backend/tests/Functional/SDK/ApiWebTestCase.php
- backend/tests/Functional/SDK/Task.php
- backend/tests/Functional/SDK/User.php
- backend/tests/Functional/Task/ChangeTaskNameTest.php
- backend/tests/Functional/Task/CompleteTaskTest.php
- backend/tests/Functional/Task/CreateCommentOnTaskTest.php
- backend/tests/Functional/Task/CreateTaskTest.php
- backend/tests/Functional/Task/ExportTasksTest.php
- backend/tests/Functional/Task/RemoveTaskTest.php
- backend/tests/Functional/Task/TaskInfoTest.php
- backend/tests/Functional/Task/TaskListTest.php
- backend/tests/Functional/User/LogoutTest.php
- backend/tests/Functional/User/SignInTest.php
- backend/tests/Functional/User/SignUpTest.php
- backend/tests/Unit/Task/Domain/TaskCommentBodyTest.php
- backend/tests/Unit/Task/Domain/TaskCommentIdTest.php
- backend/tests/Unit/Task/Domain/TaskIdTest.php
- backend/tests/Unit/Task/Domain/TaskNameTest.php
- backend/tests/Unit/Task/Domain/TaskTest.php
- backend/tests/Unit/User/Domain/UserEmailTest.php
> Актуализировал конфиг php-cs-fixer

- .editorconfig
Про trim_trailing_whitespace для md файлов http://jonasbn.github.io/til/editorconfig/markdown.html
> Добавил .editorconfig

- backend/src/Task/Http/Export/Csv/CsvExporter.php
- backend/src/Task/Http/Export/ExportTasks.php
- backend/src/Task/Http/Export/Exporter.php
- backend/src/Task/Http/Export/Xml/XmlExporter.php
> feat(taskExporter): Сделал формирование экспортеров в конструкторе ключам, и их вызов по ключам

- backend/deptrac.yaml
- backend/src/Infrastructure/ApiException/ApiErrorCode.php
- backend/src/User/SignIn/Http/Authenticator/UserChecker.php
- backend/src/User/SignIn/config.php
- backend/src/User/SignUp/Command/ConfirmEmail.php
- backend/src/User/SignUp/Domain/User.php
- backend/src/User/SignUp/Domain/UserEmail.php
- backend/tests/Functional/SDK/User.php
- backend/tests/Functional/User/SignInTest.php
> feat(user): Добавил при авторизации проверку - подтвержден ли email

- backend/src/Task/Command/Comment/Add/AddCommentOnTask.php
- backend/src/Task/Command/CompleteTask.php
- backend/src/Task/Command/CreateTask/CreateTask.php
- backend/src/Task/Command/RemoveTask.php
- backend/src/Task/Command/UpdateTaskName/UpdateTaskName.php
- backend/src/Task/Domain/Task.php
> feat(logs): Добавил логирование для задач

- backend/config/packages/doctrine.yaml
- backend/openapi.yaml
- backend/src/Article/Http/Admin/ArticleArgumentValueResolver.php
- backend/src/Article/Http/Admin/InfoAction.php
- backend/src/Article/Http/Admin/RemoveAction.php
- backend/src/Article/Http/Admin/UpdateAction.php
- backend/src/Task/Http/Comment/AddCommentOnTaskAction.php
- backend/src/Task/Http/Comment/TaskCommentsListAction.php
- backend/src/Task/Http/CompleteTaskAction.php
- backend/src/Task/Http/RemoveTaskAction.php
- backend/src/Task/Http/TaskArgumentValueResolver.php
- backend/src/Task/Http/TaskInfoAction.php
- backend/src/Task/Http/UpdateTaskNameAction.php
> feat(symfony): Изменил роуты, openapi, конфиг

- backend/src/Infrastructure/Pagination/PaginationRequest.php
- backend/src/Infrastructure/Pagination/PaginationRequestArgumentResolver.php
- backend/tests/Unit/Infrastructure/Pagination/PaginationRequestTest.php
> feat(pagination): Добавил объект пагинации и резолвер для него

- backend/phpunit.xml
- backend/tests/Command/SendUncompletedTaskCommandTest.php
- backend/tests/Functional/Article/Admin/ArticleInfoTest.php
- backend/tests/Functional/Article/Admin/ArticleListTest.php
- backend/tests/Functional/Article/Admin/CreateArticleTest.php
- backend/tests/Functional/Article/Admin/RemoveArticleTest.php
- backend/tests/Functional/Article/Admin/UpdateArticleTest.php
- backend/tests/Functional/Article/ArticleInfoTest.php
- backend/tests/Functional/Article/ArticleListTest.php
- backend/tests/Functional/SDK/ApiWebTestCase.php
- backend/tests/Functional/Task/ChangeTaskNameTest.php
- backend/tests/Functional/Task/CompleteTaskTest.php
- backend/tests/Functional/Task/CreateCommentOnTaskTest.php
- backend/tests/Functional/Task/CreateTaskTest.php
- backend/tests/Functional/Task/ExportTasksTest.php
- backend/tests/Functional/Task/RemoveTaskTest.php
- backend/tests/Functional/Task/TaskInfoTest.php
- backend/tests/Functional/Task/TaskListTest.php
- backend/tests/Functional/User/ConfirmEmailTest.php
- backend/tests/Functional/User/LogoutTest.php
- backend/tests/Functional/User/SignInTest.php
- backend/tests/Functional/User/SignUpTest.php
- backend/tests/Unit/Infrastructure/Pagination/PaginationRequestTest.php
- backend/tests/Unit/Task/Domain/TaskCommentBodyTest.php
- backend/tests/Unit/Task/Domain/TaskCommentIdTest.php
- backend/tests/Unit/Task/Domain/TaskIdTest.php
- backend/tests/Unit/Task/Domain/TaskNameTest.php
- backend/tests/Unit/Task/Domain/TaskTest.php
- backend/tests/Unit/User/Domain/UserEmailTest.php
- docker/manage.bash
> feat(tests): Добавил аннотацию testdox для всех тестов

- backend/openapi.yaml
- backend/src/Task/Http/Export/ExportTaskAction.php
- backend/src/Task/Http/Export/ExportTasks.php
- backend/src/Task/Http/TaskListAction.php
- backend/src/Task/Query/Task/FindAllByUserId/FindAllTasksByUserId.php
- backend/src/Task/Query/Task/FindAllByUserId/FindAllTasksByUserIdQuery.php
- backend/tests/Functional/SDK/Task.php
- backend/tests/Functional/Task/ExportTasksTest.php
- backend/tests/Functional/Task/TaskListTest.php
> feat(pagination): Добавил пагинацию для задач

- backend/migrations/Version20230209163744.php
- backend/openapi.yaml
- backend/src/Infrastructure/Phone.php
- backend/src/User/Profile/Command/SaveProfile/SaveProfile.php
- backend/src/User/Profile/Command/SaveProfile/SaveProfileCommand.php
- backend/src/User/Profile/Domain/Profile.php
- backend/src/User/Profile/Domain/ProfileId.php
- backend/src/User/Profile/Domain/Profiles.php
- backend/src/User/Profile/Http/ProfileInfoAction.php
- backend/src/User/Profile/Http/ProfileSaveAction.php
- backend/src/User/Profile/Query/FindByUserId/FindProfileByUserId.php
- backend/src/User/Profile/Query/FindByUserId/FindProfileByUserIdQuery.php
- backend/src/User/Profile/Query/FindByUserId/ProfileData.php
- backend/tests/Functional/SDK/Profile.php
- backend/tests/Functional/User/Profile/ProfileInfoTest.php
- backend/tests/Functional/User/Profile/ProfileSaveTest.php
- backend/tests/Functional/User/SignIn/LogoutTest.php
- backend/tests/Functional/User/SignIn/SignInTest.php
- backend/tests/Functional/User/SignUp/ConfirmEmailTest.php
- backend/tests/Functional/User/SignUp/SignUpTest.php
- backend/tests/Unit/Infrastructure/PhoneTest.php
- backend/tests/Unit/User/Profile/Domain/ProfileIdTest.php
- backend/tests/Unit/User/SignUp/Domain/UserEmailTest.php
> feat(profile): Добавил подмодуль Profile в модуле User

- backend/openapi.yaml
> feat(openapi): Вынес ответы и запросы в компоненты

- docker/backend/.env.dist
> fix(mailhog): Подправил MAILER_DSN для получения сообщений в mailhog

- backend/openapi.yaml
> fix(openapi): Пофиксил варнинги

- .github/workflows/check-code-quality.yml
- .gitignore
- docker/bin/replace_env.bash
- docker/docker-compose.local.yml
- manage.bash
> feat(manageBash): Вынес manage.bash в корень

- backend/composer.json
- backend/composer.lock
- backend/config/bundles.php
- backend/src-dev/Maker/CRUDGenerator.php
- backend/src-dev/Maker/CustomGenerator.php
- backend/src-dev/Maker/CustomStr.php
- backend/src-dev/Maker/DependencyInjection/MakerExtension.php
- backend/src-dev/Maker/Doctrine/EntityClassGeneratorForModule.php
- backend/src-dev/Maker/EntityGenerator.php
- backend/src-dev/Maker/Maker/MakeModule.php
- backend/src-dev/Maker/Resources/config/custom_makers.xml
- backend/src-dev/Maker/Resources/config/custom_services.xml
- backend/src-dev/Maker/Resources/config/makers.xml
- backend/src-dev/Maker/Resources/config/services.xml
- backend/src-dev/Maker/Resources/help/MakeModule.txt
- backend/src-dev/Maker/Resources/skeleton/domain/Entity.tpl.php
- backend/src-dev/Maker/Resources/skeleton/domain/Repository.tpl.php
- backend/src-dev/Maker/Resources/skeleton/http/EntityArgumentValueResolver.tpl.php
- backend/src-dev/Maker/Resources/skeleton/http/InfoAction.tpl.php
- backend/src-dev/Maker/Resources/skeleton/http/RemoveAction.tpl.php
- backend/src-dev/Maker/Resources/skeleton/http/create/CreateAction.tpl.php
- backend/src-dev/Maker/Resources/skeleton/http/create/CreateRequest.tpl.php
- backend/src-dev/Maker/Resources/skeleton/http/update/UpdateAction.tpl.php
- backend/src-dev/Maker/Resources/skeleton/http/update/UpdateRequest.tpl.php
- backend/symfony.lock
> feat(maker): Добавил кастомный Maker

- docker/docker-compose.local.yml
- manage.bash
> fix(manage): Исправил runBackend который перезапускал mysql

- backend/php-cs-fixer-config.php
- backend/src-dev/PHPCsFixer/Comment/ClassDocCommentFixer.php
- backend/tests/Functional/SDK/ApiWebTestCase.php
> feat(php-cs-fixer): Добавил кастомный фиксер на обязательные комментарии

- backend/src-dev/Infrastructure/ConsoleCommand/OpenApiRoutesDiffCommand.php
- backend/src-dev/Infrastructure/di.php
- backend/src/Infrastructure/Kernel.php
> refactor(command): Перенес OpenApiRoutesDiffCommand в src-dev

- backend/composer.lock
- backend/src-dev/Maker/EntityGenerator.php
- backend/symfony.lock
- docker/backend/Dockerfile
- docker/docker-compose.local.yml
> build(update-deps): Обновлены пакеты композера, версии в докерфайлах

- backend/src-dev/Maker/CRUDGenerator.php
- backend/src-dev/Maker/Resources/skeleton/http/InfoAction.tpl.php
- backend/src-dev/Maker/Resources/skeleton/http/RemoveAction.tpl.php
- backend/src-dev/Maker/Resources/skeleton/http/create/CreateAction.tpl.php
- backend/src-dev/Maker/Resources/skeleton/http/update/UpdateAction.tpl.php
> feat(maker): Добавил тип запроса для ручек

- backend/src-dev/Maker/Resources/config/custom_makers.xml
- backend/src-dev/Maker/Resources/config/custom_services.xml
- backend/src-dev/Maker/Resources/skeleton/tests/CreateTest.tpl.php
- backend/src-dev/Maker/Resources/skeleton/tests/InfoTest.tpl.php
- backend/src-dev/Maker/Resources/skeleton/tests/RemoveTest.tpl.php
- backend/src-dev/Maker/Resources/skeleton/tests/SDK.tpl.php
- backend/src-dev/Maker/Resources/skeleton/tests/UpdateTest.tpl.php
- backend/src-dev/Maker/SimpleModule/FunctionalTestsGenerator.php
- backend/src-dev/Maker/SimpleModule/MakeModule.php
> feat(maker, tests): Добавил генерацию тестов для модуля

- backend/rector.php
- backend/src-dev/Rector/OneFlushInClassRector.php
- backend/src/User/Profile/Command/SaveProfile/CreateProfile.php
- backend/src/User/Profile/Command/SaveProfile/SaveProfile.php
- backend/src/User/Profile/Command/SaveProfile/UpdateProfile.php
> feat(rector): Добавил кастомный ректор на 2 флаша в одном классе

- backend/src-dev/Maker/Resources/skeleton/domain/Entity.tpl.php
- backend/src-dev/Maker/Resources/skeleton/tests/InfoTest.tpl.php
- backend/src-dev/Maker/Resources/skeleton/tests/RemoveTest.tpl.php
- backend/src-dev/Maker/Resources/skeleton/tests/UpdateTest.tpl.php
- backend/src-dev/Maker/SimpleModule/FunctionalTestsGenerator.php
- backend/src-dev/Maker/Vendor/EntityClassGeneratorForModule.php
> feat(maker): Заменил Uuid:v4 на создание uuid 7й версии

- backend/src/Task/Http/Export/ExportTasks.php
- backend/src/Task/Http/Export/Exporter.php
> feat(tasks-export): Убрал тег для экспортеров

- backend/src/Task/Command/Comment/Add/AddCommentOnTask.php
- backend/src/Task/Command/CompleteTask.php
- backend/src/Task/Command/CreateTask/CreateTask.php
- backend/src/Task/Command/RemoveTask.php
- backend/src/Task/Command/UpdateTaskName/UpdateTaskName.php
- backend/src/Task/Http/Comment/AddCommentOnTaskAction.php
- backend/src/Task/Http/CompleteTaskAction.php
- backend/src/Task/Http/CreateTask/CreateTaskAction.php
- backend/src/Task/Http/RemoveTaskAction.php
- backend/src/Task/Http/UpdateTaskNameAction.php
- backend/src/User/Profile/Command/SaveProfile/CreateProfile.php
- backend/src/User/Profile/Command/SaveProfile/UpdateProfile.php
- backend/src/User/Profile/Http/ProfileSaveAction.php
- backend/src/User/SignIn/Command/CreateToken.php
- backend/src/User/SignIn/Command/DeleteToken.php
- backend/src/User/SignIn/Http/LogoutAction.php
- backend/src/User/SignIn/Http/SignInAction.php
- backend/src/User/SignUp/Command/ConfirmEmail.php
- backend/src/User/SignUp/Command/SignUp.php
- backend/src/User/SignUp/Http/ConfirmEmailAction.php
- backend/src/User/SignUp/Http/SignUpAction.php
> feat(flush): Перенес флаш из сервисов в ручки

- README.md
> feat(README): Изменил в README версию php с 8.1 на 8.2

- backend/migrations/Version20230308162807.php
- backend/openapi.yaml
- backend/src/Infrastructure/Email.php
- backend/src/Setting/Command/SaveSetting.php
- backend/src/Setting/Command/SaveSettingCommand.php
- backend/src/Setting/Domain/Setting.php
- backend/src/Setting/Domain/SettingNotFoundException.php
- backend/src/Setting/Domain/SettingType.php
- backend/src/Setting/Domain/Settings.php
- backend/src/Setting/Http/Admin/ListAction.php
- backend/src/Setting/Http/Admin/SettingListData.php
- backend/src/Setting/Http/Admin/SettingSaveAction.php
- backend/src/Setting/Http/SettingList/SettingListAction.php
- backend/src/Setting/Http/SettingList/SettingListData.php
- backend/src/Task/Domain/TaskCommentBody.php
- backend/src/Task/Domain/TaskName.php
- backend/src/User/Profile/Query/FindByUserId/FindProfileByUserId.php
- backend/src/User/SignIn/Http/Authenticator/ApiTokenAuthenticator.php
- backend/src/User/SignUp/Domain/ConfirmToken.php
- backend/src/User/SignUp/Domain/UserPassword.php
- backend/tests/Functional/SDK/Setting.php
- backend/tests/Functional/Setting/Admin/ListTest.php
- backend/tests/Functional/Setting/Admin/SettingSaveTest.php
- backend/tests/Functional/Setting/SettingListTest.php
> feat(setting): Добавил модуль настройки

- backend/composer.json
- backend/composer.lock
- backend/config/packages/translation.yaml
- backend/openapi.yaml
- backend/src/Article/Http/Admin/CreateAction.php
- backend/src/Article/Http/Admin/UpdateAction.php
- backend/src/Article/translations/messages.ru.php
- backend/src/Infrastructure/ApiException/CreateExceptionJsonResponse.php
- backend/src/Task/Console/SendUncompletedTaskToUser.php
- backend/src/Task/translations/messages.ru.php
- backend/src/User/SignIn/Http/Authenticator/UserChecker.php
- backend/src/User/SignUp/Command/SignUp.php
- backend/src/User/SignUp/Domain/User.php
- backend/src/User/SignUp/Notification/SendConfirmEmailToken.php
- backend/src/User/translations/messages.ru.php
- backend/symfony.lock
- backend/templates/emails/confirm.html.twig
- backend/templates/emails/uncompleted-tasks.html.twig
> feat(i18n): добавление компонента translator

- backend/src-dev/Maker/Resources/skeleton/http/create/CreateRequest.tpl.php
- backend/src-dev/Maker/Resources/skeleton/http/update/UpdateRequest.tpl.php
- backend/src/Article/Http/Admin/CreateRequest.php
- backend/src/Article/Http/Admin/UpdateRequest.php
- backend/src/Infrastructure/ApiRequestResolver/ApiRequest.php
- backend/src/Infrastructure/ApiRequestResolver/ApiRequestArgumentValueResolver.php
- backend/src/Setting/Command/SaveSettingCommand.php
- backend/src/Task/Command/Comment/Add/AddCommentOnTaskCommand.php
- backend/src/Task/Command/CreateTask/CreateTaskCommand.php
- backend/src/Task/Command/UpdateTaskName/UpdateTaskNameCommand.php
- backend/src/User/Profile/Command/SaveProfile/SaveProfileCommand.php
- backend/src/User/RecoveryPassword/Command/GenerateRecoveryTokenCommand.php
- backend/src/User/RecoveryPassword/Command/RecoverPasswordCommand.php
- backend/src/User/SignUp/Command/SignUpCommand.php
> feat(ApiRequest): Переделал ApiRequest на атрибут

- backend/openapi.yaml
- backend/src/Article/Http/ArticleList/ArticleListAction.php
- backend/src/Infrastructure/Pagination/PaginationRequest.php
- backend/src/Infrastructure/Pagination/PaginationRequestArgumentResolver.php
- backend/src/Infrastructure/Pagination/PaginationResponse.php
- backend/src/Task/Http/Export/ExportTaskAction.php
- backend/src/Task/Http/Export/ExportTasks.php
- backend/src/Task/Http/TaskList/TaskListAction.php
- backend/src/Task/Query/Task/FindAllByUserId/CountAllTasksByUserId.php
- backend/src/Task/Query/Task/FindAllByUserId/Filter.php
- backend/src/Task/Query/Task/FindAllByUserId/FindAllTasksByUserId.php
- backend/src/Task/Query/Task/FindAllByUserId/FindAllTasksByUserIdQuery.php
- backend/tests/Functional/Article/ArticleListTest.php
- backend/tests/Functional/SDK/Task.php
- backend/tests/Functional/Task/ExportTasksTest.php
- backend/tests/Functional/Task/TaskListTest.php
- backend/tests/Unit/Infrastructure/Pagination/PaginationRequestTest.php
- backend/tests/Unit/Infrastructure/Pagination/PaginationResponseTest.php
> feat(pagination): Отрефакторил пагинацию для задач

- backend/rector.php
> draft(rector): Обновил код до Symfony 6.2 с помощью ректора

- Makefile
> refactor(makefile): убрал флаг -T

- backend/rector.php
- backend/src-dev/Maker/DependencyInjection/MakerExtension.php
- backend/src-dev/Maker/Vendor/EntityGenerator.php
- backend/src-dev/PHPCsFixer/Comment/ClassDocCommentFixer.php
- backend/src-dev/PHPCsFixer/PhpUnit/DocCommentHelper.php
- backend/src-dev/PHPCsFixer/PhpUnit/TestdoxFixer.php
- backend/src-dev/PHPCsFixer/PhpUnit/TestdoxForMethods.php
- backend/src/Article/Domain/Article.php
> Добавил новые правила для ректора

- backend/src/Infrastructure/ApiRequestResolver/ApiRequestArgumentValueResolver.php
> fix(infra): Починил типизацию ApiRequest

- backend/migrations/Version20230508072251.php
- backend/openapi.yaml
- backend/src/Seo/Command/SaveSeo.php
- backend/src/Seo/Command/SaveSeoCommand.php
- backend/src/Seo/Domain/Seo.php
- backend/src/Seo/Domain/SeoCollection.php
- backend/src/Seo/Domain/SeoResourceType.php
- backend/src/Seo/Http/Admin/SeoSaveAction.php
- backend/src/Seo/Http/SeoAction.php
- backend/src/Seo/Http/SeoData.php
- backend/tests/Functional/SDK/Seo.php
- backend/tests/Functional/Seo/Admin/SeoSaveTest.php
- backend/tests/Functional/Seo/SeoTest.php
> feat(seo): Подключил модуль SEO V1

- backend/src/Article/Http/InfoAction.php
- backend/src/Seo/Http/SeoAction.php
- backend/src/Task/Http/Comment/TaskCommentsListAction.php
- backend/src/Task/Http/Export/ExportTaskAction.php
- backend/src/Task/Http/TaskInfoAction.php
- backend/src/User/SignIn/Http/LogoutAction.php
- backend/src/User/SignUp/Http/ConfirmEmailAction.php
А если еще вот так заморочиться?
> Добавил всем ValueResolver

- backend/src/Infrastructure/Kernel.php
Достаточно будет константу наполнять без дописывания кода.
META: #94158
> В Kernel вынес доступные сервисы в константу

- backend/composer.json
- backend/composer.lock
- backend/symfony.lock
> refactor(composer): удалены лишние пакеты

- backend/php-cs-fixer-config.php
> feat(fixer): правило, проверяющее наличие declare(strict_types=1);

- Makefile
> feat(makefile): запуск только одного теста

- backend/src/Infrastructure/EventSubscriber/ExceptionEventSubscriber.php
- backend/src/Infrastructure/EventSubscriber/MailerSubscriber.php
- backend/src/Infrastructure/EventSubscriber/OpenApiValidateSubscriber.php
- backend/src/Infrastructure/EventSubscriber/ResponseEventSubscriber.php
- backend/src/Infrastructure/ValueObject/Email.php
- backend/src/Infrastructure/ValueObject/Phone.php
- backend/src/Infrastructure/ValueObject/ValueObject.php
- backend/src/Task/Domain/TaskCommentBody.php
- backend/src/Task/Domain/TaskCommentId.php
- backend/src/Task/Domain/TaskId.php
- backend/src/Task/Domain/TaskName.php
- backend/src/User/Profile/Command/SaveProfile/CreateProfile.php
- backend/src/User/Profile/Command/SaveProfile/UpdateProfile.php
- backend/src/User/Profile/Domain/Profile.php
- backend/src/User/Profile/Domain/ProfileId.php
- backend/src/User/SignUp/Command/SignUp.php
- backend/src/User/SignUp/Domain/ConfirmToken.php
- backend/src/User/SignUp/Domain/User.php
- backend/src/User/SignUp/Domain/UserId.php
- backend/src/User/SignUp/Domain/UserPassword.php
- backend/tests/Functional/SDK/ApiWebTestCase.php
- backend/tests/Unit/Infrastructure/EmailTest.php
- backend/tests/Unit/Infrastructure/PhoneTest.php
> refactor(Infrastructure): сгруппировал классы в Infrastructure

- backend/composer.lock
- backend/config/packages/doctrine.yaml
- backend/php-cs-fixer-config.php
- backend/src-dev/Maker/SimpleModule/MakeModule.php
- backend/src-dev/Maker/Vendor/EntityGenerator.php
- backend/src/User/RecoveryPassword/Http/RecoverPasswordAction.php
- backend/src/User/SignUp/Http/SignUpAction.php
> refactor(composer): обновлены все пакеты, пофикшены ошибки и деприкейшены

- .github/workflows/check-code-quality.yml
- Makefile
- backend/.spectral.yaml
- backend/openapi.yaml
- docker/docker-compose.local.yml
> feat(spectral): Подключить spectral для проверки схемы апи

- backend/src/Infrastructure/EventSubscriber/OpenApiValidateSubscriber.php
- backend/tests/Functional/Article/Admin/CreateArticleTest.php
- backend/tests/Functional/Article/Admin/UpdateArticleTest.php
- backend/tests/Functional/SDK/ApiWebTestCase.php
- backend/tests/Functional/Seo/Admin/SeoSaveTest.php
- backend/tests/Functional/Setting/Admin/SettingSaveTest.php
- backend/tests/Functional/Task/ChangeTaskNameTest.php
- backend/tests/Functional/Task/CreateTaskTest.php
- backend/tests/Functional/User/Profile/ProfileSaveTest.php
- backend/tests/Functional/User/RecoveryPassword/RecoverPasswordTest.php
- backend/tests/Functional/User/SignIn/SignInTest.php
- backend/tests/Functional/User/SignUp/SignUpTest.php
- docker/backend/.env.dist
переименованы константы
Meta: #94959
> feat(api-validation): добавлен параметр для управления валидацией схемы API через ENV

- Makefile
> feat(makefile): вынес команду для создания модуля в Makefile

- Makefile
> refactor(makefile): добавил описание для module

- backend/composer.json
- docker/backend/Dockerfile
конфиг для брошенных пакетов при аудите, зафиксированная версия композера
Meta: #95061
> feat(composer): конфиг для брошенных пакетов при аудите

- backend/src-dev/Infrastructure/EventSubscriber/TestExceptionEventSubscriber.php
- backend/src-dev/Infrastructure/di.php
- backend/src/Infrastructure/EventSubscriber/ExceptionEventSubscriber.php
> 95065 exception api validator

- backend/.env
- backend/config/packages/doctrine.yaml
- backend/symfony.lock
> feat(composer): обновленные рецепты

- docker/docker-compose.local.yml
> refactor(docker): убрал наследование у backend-cli

- README.md
> refactor(readme): изменил пути к конфигам в readme

- backend/src/Setting/Http/Admin/ListAction.php
- backend/src/Setting/Http/SettingList/SettingListAction.php
- backend/src/Task/Http/Export/Csv/CsvExporter.php
- backend/src/Task/Http/Export/Xml/XmlExporter.php
> refactor(types): рефакторинг типов, вместо Generator iterable

- backend/src/Infrastructure/EventSubscriber/OpenApiValidateSubscriber.php
> fix (api-validation): пофиксил валидацию GET запросов в тестах

- backend/src-dev/openapi.yaml
> refactor(openapi): убрал все refs, которые использовались 1 раз

- backend/migrations/Version20230308162807.php
- backend/src/Setting/Domain/SettingType.php
- backend/src/Setting/Domain/Settings.php
- backend/src/Setting/Http/SettingList/SettingListAction.php
- backend/tests/Functional/SDK/Setting.php
- backend/tests/Functional/Setting/Admin/ListTest.php
- backend/tests/Functional/Setting/SettingListTest.php
> refactor(setting): отрефакторил модуль Setting согласно патчу

- backend/composer.json
- backend/composer.lock
- docker/backend/Dockerfile
- docker/docker-compose.local.yml
- docker/mysql/Dockerfile
- docker/nginx/Dockerfile
> feat (php): обновлены php, composer, nginx и mysql

- backend/src-dev/Rector/rector.config.php
- backend/src/Article/Http/Admin/CreateAction.php
- backend/src/Article/Http/Admin/InfoAction.php
- backend/src/Article/Http/Admin/ListAction.php
- backend/src/Article/Http/Admin/RemoveAction.php
- backend/src/Article/Http/Admin/UpdateAction.php
- backend/src/Article/Http/ArticleList/ArticleListAction.php
- backend/src/Article/Http/InfoAction.php
- backend/src/Seo/Http/Admin/SeoSaveAction.php
- backend/src/Seo/Http/SeoAction.php
- backend/src/Setting/Http/Admin/ListAction.php
- backend/src/Setting/Http/Admin/SettingSaveAction.php
- backend/src/Setting/Http/SettingList/SettingListAction.php
- backend/src/Task/Http/Comment/AddCommentOnTaskAction.php
- backend/src/Task/Http/Comment/TaskCommentsListAction.php
- backend/src/Task/Http/CompleteTaskAction.php
- backend/src/Task/Http/CreateTask/CreateTaskAction.php
- backend/src/Task/Http/Export/ExportTaskAction.php
- backend/src/Task/Http/RemoveTaskAction.php
- backend/src/Task/Http/TaskInfoAction.php
- backend/src/Task/Http/TaskList/TaskListAction.php
- backend/src/Task/Http/UpdateTaskNameAction.php
- backend/src/User/Profile/Http/ProfileInfoAction.php
- backend/src/User/Profile/Http/ProfileSaveAction.php
- backend/src/User/RecoveryPassword/Http/RecoverPasswordAction.php
- backend/src/User/RecoveryPassword/Http/RequestPasswordRecoveryAction.php
- backend/src/User/SignIn/Http/LogoutAction.php
- backend/src/User/SignIn/Http/SignInAction.php
- backend/src/User/SignUp/Http/ConfirmEmailAction.php
- backend/src/User/SignUp/Http/SignUpAction.php
> feat (rector): добавил правило SymfonySetList::SYMFONY_64

- Makefile
> refactor(makefile): добавил новые команды в makefile

- backend/src-dev/Tests/Functional/PingHttpActionTest.php
- backend/src-dev/deptrac-module.yaml
- backend/src-dev/openapi.yaml
- backend/src/Ping/Http/PingHttpAction.php
- backend/src/Ping/Http/Pong.php
> feat (api): добавил модуль Ping

- backend/src-dev/Tests/Functional/SDK/Task.php
- backend/src-dev/Tests/Functional/Task/TaskListTest.php
- backend/src-dev/openapi.yaml
- backend/src/Infrastructure/Response/ApiListObjectResponse.php
- backend/src/Task/Http/TaskList/TaskListAction.php
- backend/src/Task/Http/TaskList/TaskListMetaData.php
> refactor(api): добавил meta в ответ для списков

- docker/docker-compose.local.yml
> refactor(docker-compose): удалил атрибут с версией

- backend/.env
- backend/bin/console
- backend/composer.lock
- backend/config/packages/dama_doctrine_test_bundle.yaml
- backend/config/packages/doctrine.yaml
- backend/config/packages/framework.yaml
- backend/config/packages/mailer.yaml
- backend/config/packages/monolog.yaml
- backend/config/packages/routing.yaml
- backend/src-dev/Tests/Functional/SDK/ApiWebTestCase.php
- backend/symfony.lock
- docker/backend/Dockerfile
> feat(config): актуализировал конфиги, обновил пакеты

- .github/workflows/check-code-quality.yml
- Makefile
- backend/src-dev/PHPCsFixer/php-cs-fixer-config.php
- backend/src-dev/PHPStan/phpstan-config.neon
- backend/src-dev/Rector/rector.config.php
- backend/src-dev/phpunit.xml
- docker/backend/Dockerfile
> fix(config): актуализировал конфиги rector, php-cs-fixer

- backend/src-dev/Tests/Functional/Infrastructure/Request/TraceIdHeaderTest.php
- backend/src/Infrastructure/Request/RequestIdListener.php
- backend/src/Infrastructure/Request/RequestIdLoggerProcessor.php
- backend/src/Ping/Http/PingHttpAction.php
> feat(request): добавил TraceId в логи и респонсы

- backend/src-dev/Tests/Functional/SDK/ApiWebTestCase.php
- backend/src-dev/openapi.yaml
- backend/src/Infrastructure/ApiException/ApiErrorResponse.php
> refactor(specs): отрефакторил спецификацию

- backend/src-dev/Tests/Command/SendUncompletedTaskCommandTest.php
- backend/src-dev/Tests/Functional/SDK/ApiWebTestCase.php
- backend/src-dev/Tests/Functional/SDK/User.php
- backend/src-dev/Tests/Functional/Task/ChangeTaskNameTest.php
- backend/src-dev/Tests/Functional/Task/CompleteTaskTest.php
- backend/src-dev/Tests/Functional/Task/CreateCommentOnTaskTest.php
- backend/src-dev/Tests/Functional/Task/ExportTasksTest.php
- backend/src-dev/Tests/Functional/Task/RemoveTaskTest.php
- backend/src-dev/Tests/Functional/Task/TaskInfoTest.php
- backend/src-dev/Tests/Functional/Task/TaskListTest.php
- backend/src-dev/Tests/Functional/User/RecoveryPassword/RecoverPasswordTest.php
- backend/src-dev/Tests/Functional/User/SignIn/SignInTest.php
- backend/src-dev/Tests/Functional/User/SignUp/ConfirmEmailTest.php
- backend/src-dev/Tests/Functional/User/SignUp/SignUpTest.php
- backend/src/User/RecoveryPassword/Command/RecoverPassword.php
- backend/src/User/RecoveryPassword/Domain/RecoveryTokenRepository.php
- backend/src/User/SignIn/Domain/UserTokenRepository.php
> feat(recovery-password): добавил удаление токенов после успешного восстановления пароля

- backend/src-dev/Tests/Functional/User/SignIn/SignInTest.php
- backend/src-dev/openapi.yaml
- backend/src/Infrastructure/ApiException/ApiErrorCode.php
- backend/src/User/SignIn/Http/SignInAction.php
> fix(signin): исправил ответ при неверном пароле

- backend/src-dev/Tests/Functional/User/ChangePassword/ChangePasswordTest.php
- backend/src-dev/Tests/Functional/User/RecoveryPassword/RecoverPasswordTest.php
- backend/src-dev/openapi.yaml
- backend/src/User/Password/Command/ChangePassword.php
- backend/src/User/Password/Command/ChangePasswordCommand.php
- backend/src/User/Password/Command/GenerateRecoveryToken.php
- backend/src/User/Password/Command/GenerateRecoveryTokenCommand.php
- backend/src/User/Password/Command/RecoverPassword.php
- backend/src/User/Password/Command/RecoverPasswordCommand.php
- backend/src/User/Password/Command/RecoveryTokenNotFoundException.php
- backend/src/User/Password/Domain/RecoveryToken.php
- backend/src/User/Password/Domain/RecoveryTokenRepository.php
- backend/src/User/Password/Http/ChangePasswordAction.php
- backend/src/User/Password/Http/ChangePasswordRequest.php
- backend/src/User/Password/Http/RecoverPasswordAction.php
- backend/src/User/Password/Http/RequestPasswordRecoveryAction.php
- backend/src/User/SignIn/Command/CreateToken.php
- backend/src/User/SignIn/Command/SignIn.php
- backend/src/User/User/Domain/UserRepository.php
> feat(user/change-password): добавил ручку смены текущего пароля

- backend/src/Setting/Command/SaveSetting.php
- backend/src/Setting/Domain/SettingsRepository.php
- backend/src/User/Password/Command/ChangePassword.php
- backend/src/User/Password/Command/RecoverPassword.php
- backend/src/User/Password/Http/RecoverPasswordAction.php
- backend/src/User/Security/Service/TokenManager.php
- backend/src/User/SignIn/Command/DeleteToken.php
- backend/src/User/SignUp/Command/ConfirmEmail.php
- backend/src/User/User/Domain/UserRepository.php
- backend/src/User/User/Domain/UserTokenRepository.php
> refactor(repositories): заменил метод get на find в репозиториях

- backend/src-dev/Infrastructure/EventSubscriber/OpenApiValidateSubscriber.php
- backend/src-dev/Infrastructure/di.php
- backend/src-dev/Tests/Functional/SDK/ApiWebTestCase.php
> refactor(infrastructure): Перенес OpenApiValidateSubscriber в src-dev

- backend/src/Infrastructure/Request/RequestLogger.php
> feat(infrastructure): Добавил логирование http запросов и ответов

- backend/src/Infrastructure/ValueObject/Phone.php
- backend/src/Mailer/Notification/EmailConfirmation/ConfirmEmailMessage.php
- backend/src/Mailer/Notification/PasswordRecovery/RecoveryPasswordMessage.php
- backend/src/User/Password/Command/ChangePasswordCommand.php
- backend/src/User/Password/Command/RecoverPasswordCommand.php
- backend/src/User/Password/Domain/RecoveryToken.php
- backend/src/User/Password/Http/ChangePasswordRequest.php
- backend/src/User/Password/Http/RecoverPasswordAction.php
- backend/src/User/Profile/Command/SaveProfile/SaveProfileCommand.php
- backend/src/User/Profile/Query/FindByUserId/ProfileData.php
- backend/src/User/SignIn/Command/SignInCommand.php
- backend/src/User/SignIn/Http/SignInRequest.php
- backend/src/User/SignIn/Http/UserTokenData.php
- backend/src/User/SignUp/Command/ConfirmEmail.php
- backend/src/User/SignUp/Command/SignUpCommand.php
- backend/src/User/SignUp/Http/ConfirmEmailAction.php
- backend/src/User/User/Domain/AuthToken.php
- backend/src/User/User/Domain/ConfirmToken.php
- backend/src/User/User/Domain/UserPassword.php
- backend/src/User/User/Query/FindUserQuery.php
- backend/src/User/User/Query/UserData.php
- backend/src/User/User/Query/UserListData.php
…альными данными
META: #1000015
> Добавил атрибут SensitiveParameter полям с конфиденциальными данными

- backend/src/Infrastructure/Request/RequestLogger.php
> refactor(infrastructure): сделал декодирование ответа для логов
